### PR TITLE
Aligned with the latest jQuery API changes

### PR DESCRIPTION
**Pull request by Mte90**
updated also the jquery autocomplete library.

I wasn't able to fix all the jQuery warning but this is an improvement after all.

### CODE REVIEW

**Comment by Mte90** [comment]
ping @rubengc

**Comment by Mte90** [comment]
Ping

**Review by rubengc — CHANGES_REQUESTED** [review]
There is no need to add this changes because your plugin or theme already checks if WordPress exists

Or at least, replace the code with the most standard way to check if WordPress exists that is:
`// Exit if accessed directly
if( !defined( 'ABSPATH' ) ) exit;`

**Review by rubengc — CHANGES_REQUESTED** [review]
not sure about this change, please, can you explain this PR?

**Comment by Mte90** [comment]
That check for `add_action` is needed if you use composer. Otherwise the php file is enqueued and crash any composer command if you use to install this library.

**Comment by Mte90** [comment]
ping

**Comment by Mte90** [comment]
ping @rubengc

**Comment by Mte90** [comment]
ping @rubengc

**Comment by Mte90** [comment]
ping

**Comment by rubengc** [comment]
Hi @Mte90 I did not used this field anymore in any projects so you can make your own merge and continue its development

If at some moment I create again a field like this will be completely different and a bit more flexible

**Comment by Mte90** [comment]
Can you mark the project as abandoned in the repo settings so it is more clear?

**Pull request closed without merging**
