### PR TITLE
Repeatable

### PR DESCRIPTION
**Pull request by Mte90**
Right now the field frontend works but is not saving the value if it is in a metabox that is repeatable.
I am trying to understand where is the issue.

### CODE REVIEW

**Comment by Mte90** [comment]
Right now the field doesn't save the value on repeatable fields and if multiple is disabled save the title of the post and not the id.
I am trying to understand what's happening but any help can be precious.

**Comment by Mte90** [comment]
I got it....
This field use the `multiple` parameter that is reserved to CMB2 so this was the reason of a lot of issues inside the field itself.
I changed to another one but is not yet finished because not save the values.

**Comment by Mte90** [comment]
I could not relax until I fix this after working all the afternoon.
Seems there was also other issues between `id` not standard and also `name` not standard.
I finished and tested and ready to be merged.

**Comment by Mte90** [comment]
just a ping

**Comment by Mte90** [comment]
ping @rubengc

**Comment by rubengc** [comment]
Hi @Mte90 

Sorry for the delayed response but I have years without using this field since I switched to Select2

I'm planning to release the CMB2 Select2 field at some moment when I get less busy from my actual work with my projetcs GamiPress  and AutomatorWP

Anyway, i will merge this pull request to let you get them added to this repo

Thank you so much for this contribution!

**Pull request merged**
